name: deploy-notebook

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-notebook:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install nbconvert jupyter

    - name: Convert notebook to HTML
      run: |
        jupyter nbconvert --to html eda.ipynb --output-dir build --output index.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
